#! python3
a=("X")
b=("|")
c=("-")

print("          ",a)
print("        ",a,a,a)
print("      ",a,a,a,a,a)
print("     ",b,"       ",b)
print("     ",b,"  abc  ",b)
print("      ",c,c,c,c,c)

print()
print()
a = input("Enter Name: ")
b = input("Home address: ")
c = input("Phone number: ")
d = input("Email Address: ")
print ()
print("Good Morning,", a)
print("Your home address is,", b)
print("Your number is,", c)
print("Your email is,", d)
print("Thank you!")
print ()
print("Output complete!")
