print("Content-Type: text/html")
print()
print("<!DOCTYPE HTML>")
print("<html>")
print("<head>")
print("<title>www.siibee.no</title>")
print("</head>")
print("<body>")
print("<h1>Hei Siri, Nice to meet you!</h1>")
print("</body>")
print("</html>")
